### ISSUE TITLE
Add aarch64 and ppc64le builds

### ISSUE THREAD

**Issue by matthewfeickert** [conda-forge/hepmc2-feedstock#8]
@Kwaizer what we could do to improve the feedstock is to add aarch64 and ppc64le builds by adding to the existing config file

https://github.com/conda-forge/hepmc2-feedstock/blob/9ac500d83544bf5e79dc04ee57696c3592273121/conda-forge.yml#L1-L6

the following

```yaml
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
  osx_arm64: osx_64
provider:
  linux_aarch64: default
  linux_ppc64le: default
test: native_and_emulated
```

This would enable more machines to be able to use the feedstock.

c.f. https://github.com/conda-forge/fastjet-feedstock/pull/13 as an example
